# Solving Linear Equation Systems with Gauß Elimination 

* Learn How to Write Markdown & LaTeX in The Jupyter Notebook<br>https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd
* How to programmatically generate markdown output in Jupyter notebooks?<br>https://stackoverflow.com/questions/36288670/how-to-programmatically-generate-markdown-output-in-jupyter-notebooks

In [22]:
import numpy as np
from IPython.display import display, Markdown, Latex, Math

In [26]:
display(Markdown('some markdown $\phi$'))
display(Markdown('*some markdown* $\phi$'))
display(Markdown('**some markdown** $\phi$'))

some markdown $\phi$

*some markdown* $\phi$

**some markdown** $\phi$

In [27]:
#from IPython.display import display, Math, Latex
display(Math(r'F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx'))

<IPython.core.display.Math object>

The following manual markdown code displays a matrix:
```
$
\begin{pmatrix}
1 & 2 & 3\\
a & b & c
\end{pmatrix}
$
```

The rendered result:

$
\begin{pmatrix}
1 & 2 & 3\\
a & b & c
\end{pmatrix}
$

**Markdown output can be created by code!**

In [29]:
s = r"1 & 2 & 3\\a & b & c"
sp = r"$\begin{pmatrix}" + s + r"\end{pmatrix}$"
display(Markdown(sp))

$\begin{pmatrix}1 & 2 & 3\\a & b & c\end{pmatrix}$

## An Example Linear Equation System ##

In [30]:
#M = np.array([[1., 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
M = np.array(
    [
        [-1., -1, 1, 0],
        [-6, 3, 0, -24],
        [0, -3, -6, -12]
    ])

M

array([[ -1.,  -1.,   1.,   0.],
       [ -6.,   3.,   0., -24.],
       [  0.,  -3.,  -6., -12.]])

In [5]:
print(M)

[[ -1.  -1.   1.   0.]
 [ -6.   3.   0. -24.]
 [  0.  -3.  -6. -12.]]


### Nice Matrix Rendering in Markdown ###

In [32]:
def Mat2MD(M, name="", idx="", fmt=""):
    matrix_string = ""
    for r in M:
        if matrix_string: matrix_string += r" \\ "
#        fmt_string = f"{x}"
        matrix_string += " & ".join([f"{x:{fmt}}" for x in r])
    if name:
        if idx:
            Mstr = name + "_" + idx + "="
        else:
            Mstr = name + "="
    else:
        Mstr = ""

    return(Mstr + r"\begin{pmatrix}" + matrix_string + r"\end{pmatrix}")

In [33]:
display(Math(Mat2MD(M,fmt=".2f")))
display(Math(Mat2MD(M,"A")))
display(Math(Mat2MD(M,"M","1")))
display(Math(Mat2MD(M,"M","k")))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### Nice LES Rendering for Gauß Elimination ###

In [34]:
def Gauss2MD(M, name="", idx="", fmt="g"):

    matrix_string = ""
    for r in M:
#        if matrix_string: matrix_string += r" \\ "
        matrix_string += " & ".join([f"{x:{fmt}}" for x in r]) + r"\\"
    if name:
        if idx:
            Mstr = name + "_" + idx + "="
        else:
            Mstr = name + "="
    else:
        Mstr = ""
        
    (m,n) = M.shape
    fmt = "{"+(n-1)*"c"+"|"+"c"+"}"
    
    return(Mstr + r"\left(\begin{array}" + fmt + matrix_string + r"\end{array}\right)")

In [35]:
display(Math(Gauss2MD(M,fmt="")))
display(Math(Gauss2MD(M,"A",fmt=".3f")))
display(Math(Gauss2MD(M,"M","1",fmt=".2e")))
display(Math(Gauss2MD(M,"M","k")))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### The Pivoting Function to Create Row Echeon Form ###

In [36]:
def Gauss_Pivot(M,from_row,to_row,pivot_col,debug=False):
    MM=M.copy()
    (m,n)=MM.shape
    r = MM[from_row][pivot_col]/MM[to_row][pivot_col]
    if debug:
        print(MM[from_row])
        print(MM[to_row])
        print(MM[from_row][pivot_col])
        print(MM[to_row][pivot_col])    
        print(r)
    if from_row == to_row:
        MM[to_row] = MM[to_row]/MM[from_row][pivot_col]
    else:
        MM[to_row] = MM[from_row] - r*MM[to_row]
    return(MM)

In [37]:
#M = np.array([[1., 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(M)
display(Math(Gauss2MD(M,"M")))

[[ -1.  -1.   1.   0.]
 [ -6.   3.   0. -24.]
 [  0.  -3.  -6. -12.]]


<IPython.core.display.Math object>

In [38]:
M1 = Gauss_Pivot(M,0,1,0)
display(Math(Gauss2MD(M1,"M_1",fmt="g")))

<IPython.core.display.Math object>

In [39]:
M2 = Gauss_Pivot(M1,1,2,1)
display(Math(Gauss2MD(M2,"M_2",fmt=".2f")))

<IPython.core.display.Math object>

In [40]:
M3 = Gauss_Pivot(M2,2,1,2)
#print(M4)
display(Math(Gauss2MD(M3,"M_3",fmt=".2f")))

<IPython.core.display.Math object>

In [41]:
M4 = Gauss_Pivot(M3,2,0,2)
#print(M4)
display(Math(Gauss2MD(M4,"M_4",fmt=".2f")))

<IPython.core.display.Math object>

In [42]:
M5 = Gauss_Pivot(M4,1,0,1)
#print(M4)
display(Math(Gauss2MD(M5,"M_5",fmt=".2f")))

<IPython.core.display.Math object>

In [18]:
M6 = Gauss_Pivot(M5,0,0,0)
display(Math(Gauss2MD(M6,"M_6",fmt=".2f")))

<IPython.core.display.Math object>

In [19]:
M7 = Gauss_Pivot(M6,1,1,1)
display(Math(Gauss2MD(M7,"M_7",fmt=".2f")))

<IPython.core.display.Math object>

In [20]:
M8 = Gauss_Pivot(M7,2,2,2)
display(Math(Gauss2MD(M8,"M_8",fmt=".2f")))

<IPython.core.display.Math object>